build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - ./scripts/ci.sh levmar
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: levmar
    source: deploy/
    target: ~
    recursive: true
    delete: false
