build:
  image: bjodah/bjodahimg20dev:v1.0.4
  commands:
    - ./scripts/ci.sh levmar
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    #- PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: levmar
    source: deploy/
    target: ~
    recursive: true
    delete: false
